In [1]:
import pandas as pd
import numpy as np

In [2]:
Orders=pd.read_excel("sample_superstore.xls",sheet_name="Orders")
People=pd.read_excel("sample_superstore.xls",sheet_name="People")
Returns=pd.read_excel("sample_superstore.xls",sheet_name="Returns")

In [3]:
Orders.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717

In [4]:
Orders_clean=Orders.copy()

In [5]:
Orders_clean.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
dtype: int64

In [6]:
Orders_clean.duplicated().sum()

np.int64(0)

In [7]:
Orders_clean.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country/Region            object
City                      object
State/Province            object
Postal Code               object
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
dtype: object

## Verifying Dates

In [8]:
Orders_clean[['Order Date','Ship Date']].head(3)

  Order Date  Ship Date
0 2023-01-03 2023-01-07
1 2023-01-04 2023-01-08
2 2023-01-04 2023-01-08

In [9]:
Orders_clean['Order Year']=Orders_clean['Order Date'].dt.year

In [10]:
Orders_clean['Order Month']=Orders_clean['Order Date'].dt.month

In [11]:
Orders_clean['Month Name']=Orders_clean['Order Date'].dt.month_name()

In [12]:
Orders_clean["Quarter"] = Orders_clean["Order Date"].dt.quarter

In [13]:
Orders_clean["Day Name"] = Orders_clean["Order Date"].dt.day_name()

## query to find the no of days it takes to ship the order

In [14]:
Orders_clean['Shipping Time']=(Orders_clean['Ship Date']-Orders_clean['Order Date'])

## Profit Margin

In [15]:
Orders_clean['Profit Margin %']=Orders_clean['Profit']/Orders_clean['Sales']*100

## Discount %

In [16]:
Orders_clean['Discount %']=Orders_clean['Discount']*100

In [17]:
Orders_clean.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Discount,Profit,Order Year,Order Month,Month Name,Quarter,Day Name,Shipping Time,Profit Margin %,Discount %
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,0.2,5.5512,2023,1,January,1,Tuesday,4 days,33.75,20.0
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,0.8,-5.4870,2023,1,January,1,Wednesday,4 days,-155.00,80.0

## Negative Sales

In [18]:
Orders_clean[Orders_clean["Sales"] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country/Region, City, State/Province, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Order Year, Order Month, Month Name, Quarter, Day Name, Shipping Time, Profit Margin %, Discount %]
Index: []

[0 rows x 29 columns]

## Negative Quantity

In [19]:
Orders_clean[Orders_clean["Quantity"] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country/Region, City, State/Province, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Order Year, Order Month, Month Name, Quarter, Day Name, Shipping Time, Profit Margin %, Discount %]
Index: []

[0 rows x 29 columns]

## Checking for Discount more than 100 %

In [20]:
Orders_clean[Orders_clean["Discount %"] > 100]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country/Region, City, State/Province, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Order Year, Order Month, Month Name, Quarter, Day Name, Shipping Time, Profit Margin %, Discount %]
Index: []

[0 rows x 29 columns]

In [21]:
Orders_clean.to_csv("Orders_Clean.csv", index=False)

## Finding Maximum Shipping Time

In [23]:
Max_shipping_time=Orders_clean['Shipping Time'].max()
Max_shipping_time

Timedelta('11 days 00:00:00')

## Average profit Margin

In [28]:
Avg_Profit_Margin=Orders_clean['Profit Margin %'].mean()
Avg_Profit_Margin

np.float64(12.221784400156013)

## Negative profit margins

In [31]:
Negative_Profit_Margin=Orders_clean['Profit Margin %']<0
Negative_Profit_Margin.value_counts()

Profit Margin %
False    8293
True     1901
Name: count, dtype: int64

In [32]:
Negative_Profit_Margin.sum()

np.int64(1901)

## Which month has the highest number of orders?

In [36]:
Orders_clean['Order ID'].groupby(Orders_clean['Month Name']).count().sort_values(ascending=False)

Month Name
November     1474
December     1470
September    1399
October       843
May           758
June          725
August        722
July          718
March         711
April         670
January       404
February      300
Name: Order ID, dtype: int64